sudo: required
services:
  - docker

before_install:
  # build from development dockerfile because they contain source code and dependencies for test execution
  - docker build -t katarinacimesa/react-test -f ./client/Dockerfile.dev ./client
# - docker build my_other_project
script:
# primary test running section
  - docker run -e CI=true katarinacimesa/react-test npm test
# - run my other tests

after_succes:
  - docker build -t katarinacimesa/multi-client ./client 
  - docker build -t katarinacimesa/multi-nginx ./nginx 
  - docker build -t katarinacimesa/multi-server ./server 
  - docker build -t katarinacimesa/multi-worker ./worker 
# log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push to dockerhub
  - docker push katarinacimesa/multi-client
  - docker push katarinacimesa/multi-nginx
  - docker push katarinacimesa/multi-server
  - docker push katarinacimesa/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-679502951545
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY